// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP444L-CNFKLY3Ko9jeMjDQNCgWx9X6zw',
    appId: '1:930525624495:web:519fe63d0daac096897c5a',
    messagingSenderId: '930525624495',
    projectId: 'todo-app-b7751',
    authDomain: 'todo-app-b7751.firebaseapp.com',
    storageBucket: 'todo-app-b7751.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATSV9BKJN6O91AgdHSlX2uSnr2OE1BTeM',
    appId: '1:930525624495:android:5d1187806fe16d80897c5a',
    messagingSenderId: '930525624495',
    projectId: 'todo-app-b7751',
    storageBucket: 'todo-app-b7751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbXUJ5qGxn30aozV8VvBCQwYo5bnQA-S4',
    appId: '1:930525624495:ios:ba4876aab4e7e5c2897c5a',
    messagingSenderId: '930525624495',
    projectId: 'todo-app-b7751',
    storageBucket: 'todo-app-b7751.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );
}
